import { Header } from "@/shared/components/shared"
import { Metadata } from "next"
import { Suspense } from "react"

export const metadata:Metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function CheckoutLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (  
        <main className="min-h-screen bg-[#F4F1EE]">
            <Suspense><Header hasSearch={false} hasCart={false}/></Suspense>
            {children}
        </main>
    )
  }